### ISSUE TITLE
Debugger is not triggering on breakpoints after setting up

### ISSUE THREAD

**Issue by gosteev** [markshust/docker-magento#350]
Hello! First of all, I want to thank you for this great docker configuration. I find it very handy and switched most of the projects I'm working on to it. 
However, I can't set up my debugger using this instruction: https://github.com/markshust/docker-magento#xdebug--phpstorm

**Description**
Can't set up my debugger

**Steps To Reproduce**
Go through the steps of this instruction https://github.com/markshust/docker-magento#xdebug--phpstorm

**Expected Result**
PHPStorm will stop on the breakpoints

**Actual Result**
PHPStorm is not stopping, I can see `waiting for incoming connections with ide key 'PHPSHORM'` text

===

**`bin/cli php -v` output:**
```
PHP 7.4.8 (cli) (built: Jul 22 2020 09:39:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.1, Copyright (c) 2002-2020, by ionCube Ltd.
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
    with blackfire v1.36.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

**PHP config**:
![image](https://user-images.githubusercontent.com/6203574/100522210-c2141300-31b1-11eb-9750-98af61c24acb.png)

**PHP server**:
![image](https://user-images.githubusercontent.com/6203574/100522330-888fd780-31b2-11eb-8701-0ef0ccc8772f.png)

**Debug configuration**:
![image](https://user-images.githubusercontent.com/6203574/100522664-52068c80-31b3-11eb-9453-d60ab2ab0fcc.png)

**Xdebug helper extension options**:
![image](https://user-images.githubusercontent.com/6203574/100522625-2388b180-31b3-11eb-8959-bca61f9fb7aa.png)

**Debug** and **DBGp Proxy** ports are set to `9001` inside PHPStorm settings

**Comment by r-martins** [comment]
Try adding `PHP_IDE_CONFIG: "serverName=ShustDocker"` in docker-compose.dev.yml.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/191149/101718989-77ba5c80-3af6-11eb-959b-274207a8703a.png">

**Comment by niziou** [comment]
It's not working for me as well, the above solution did not work out for me as well. I have used php72-fpm2 if it matters

**Comment by r-martins** [comment]
Double check your PhpStorm settings..
1. The port must be the same configured in php.ini
<img width="511" alt="image" src="https://user-images.githubusercontent.com/191149/102025847-b39f3b80-3dee-11eb-88cd-02064341f41d.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/191149/102025861-c44fb180-3dee-11eb-85cb-6096c8e0ab60.png">

2. Check the server address
<img width="982" alt="image" src="https://user-images.githubusercontent.com/191149/102025876-d9c4db80-3dee-11eb-8a96-5aa8a9e51a49.png">
as per the image in my previous message

3. Remember to enable xdebug
bin/xdebug enable
and check if it's enabled with `bin/cli php -v`
<img width="962" alt="image" src="https://user-images.githubusercontent.com/191149/102025913-0547c600-3def-11eb-9dfd-bf52cd85d9da.png">

**Comment by niziou** [comment]
After adding this php ide config and chaning server name the xdebug started. Thanks for help

**Comment by vy-shmal** [comment]
I have the same problem, cant make xdebug work.

OS
**I have Ubuntu 20.04.1 LTS**  

I am trying to configure phpstorm for the remote PHP Remote Debug. I followed the configuration on the documentation, with no success, I also made the configuration from above but still nothing. 

Here is my config.

![Screenshot from 2020-12-18 11-20-13](https://user-images.githubusercontent.com/14836183/102597393-3db70f00-4123-11eb-9e2c-aebb331c2a8c.png)

![Screenshot from 2020-12-18 11-20-28](https://user-images.githubusercontent.com/14836183/102597403-40b1ff80-4123-11eb-91f9-016c5e6e15c1.png)

![Screenshot from 2020-12-18 11-21-16](https://user-images.githubusercontent.com/14836183/102597408-43145980-4123-11eb-990f-ef81c981595d.png)

![Screenshot from 2020-12-18 11-21-29](https://user-images.githubusercontent.com/14836183/102597414-44de1d00-4123-11eb-9165-c0a00bf7db1c.png)

![Screenshot from 2020-12-18 11-23-04](https://user-images.githubusercontent.com/14836183/102597498-6ccd8080-4123-11eb-9678-269980e500e8.png)

**Comment by r-martins** [comment]
What about your [.yml file](https://github.com/markshust/docker-magento/issues/350#issuecomment-742219682)?
And your [php.ini config](https://github.com/markshust/docker-magento/issues/350#issuecomment-744079592)?

**Comment by ssstankiewicz** [comment]
@vy-shmal  On Linux don't forget about uncommented these two lines in docker-compose.dev.yml
![docker](https://user-images.githubusercontent.com/25231802/103305065-85367880-4a0a-11eb-9cbf-f250d1000a01.png)

**Comment by vy-shmal** [comment]
Yes that was it! Thank you a lot @ssstankiewicz  .

**Comment by vy-shmal** [comment]
> What about your [.yml file](https://github.com/markshust/docker-magento/issues/350#issuecomment-742219682)?
> And your [php.ini config](https://github.com/markshust/docker-magento/issues/350#issuecomment-744079592)?

Sorry @r-martins for the delay of the response, now I found time to reply. 

php.ini is the default of the docker with xdebug enabled. 
the .yml was the default of docker 

Here is the  docker-compose.dev.yml with the solution above:

```# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 34.2.0

version: "3"

services:
  app:
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ./src/app/code:/var/www/html/app/code:cached
      - ./src/app/design:/var/www/html/app/design:cached
      - ./src/app/etc:/var/www/html/app/etc:cached
      - ./src/composer.json:/var/www/html/composer.json:cached
      - ./src/composer.lock:/var/www/html/composer.lock:cached
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      #- ./src/auth.json:/var/www/html/auth.json:cached
      #- ./src/m2-hotfixes:/var/www/html/m2-hotfixes:cached
      #- ./src/patches:/var/www/html/patches:cached
      #- ./src/var/log:/var/www/html/var/log:cached
      #- ./src/var/report:/var/www/html/var/report:cached
      # To sync your SSH to the container, uncomment the following line:
      #- ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      # Linux only: remove the above lines and mount the entire src directory with:
      - ./src:/var/www/html:cached

  phpfpm:
    volumes: *appvolumes
    environment:
      PHP_IDE_CONFIG: "serverName=ShustDocker"
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  volumes: *appvolumes
```

Thank you for your time.

**Comment by markshust** [comment]
It appears this issue is resolved. 

I initially created this repo for Mac, but since then 5 years has passed, and it has become popular on Linux as well. I'll try to improve the setup process for Linux users so more of this is automated. It could potentially also help out users on Windows WSL. 

Closing this as it appears to be resolved/non-issue.

**Comment by gosteev** [comment]
an issue is not resolved.
I tried adding `PHP_IDE_CONFIG` and `extra_hosts` to docker-compose file, triple-checked all the settings, still no luck :(

`docker run --rm alpine ip route | awk 'NR==1 {print $3}'` prints 172.17.0.1

![image](https://user-images.githubusercontent.com/6203574/103540093-d5498b00-4ea1-11eb-8d13-5618d7afe57c.png)

**Comment by markshust** [comment]
Reopening this issue for visibility.

Is anyone else having problems running Xdebug on Linux?

These lines within the docker-compose.yml file should do the trick:

```
...
  phpfpm:
    volumes: *appvolumes
    environment:
      PHP_IDE_CONFIG: "serverName=ShustDocker"
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
      ...
```

Other than that, I'm not sure what else it could be. No other changes should be needed, so if you made any other changes I'd recommend backing them out.

**Comment by pykettk** [comment]
> Is anyone else having problems running Xdebug on Linux?

Yeah, still a problem for me on Ubuntu 20.04.1 and Docker version 20.10.2, build 2291f61.

The suggested changes above do not resolve this issue for me either. PhpStorm sits in a constant state of waiting for incoming connections.

**Comment by markshust** [comment]
This should be resolved on the latest images.

**Comment by Stoyvo** [comment]
This resolved it for me: https://www.jetbrains.com/help/phpstorm/troubleshooting-php-debugging.html#debugger-does-not-work-nginx

**Comment by niners52** [comment]
> > Is anyone else having problems running Xdebug on Linux?
> 
> Yeah, still a problem for me on Ubuntu 20.04.1 and Docker version 20.10.2, build 2291f61.
> 
> The suggested changes above do not resolve this issue for me either. PhpStorm sits in a constant state of waiting for incoming connections.

@pykettk Did you ever get this resolved?

**Comment by markshust** [comment]
@pykettk I think @niners52 & I resolved this issue. I'll be pushing out an update momentarily, but it has to do with extra_hosts and a DNS entry not setup for host.docker.internal.

**Comment by markshust** [comment]
This should be fully resolved in 41.0.2 https://github.com/markshust/docker-magento/blob/master/CHANGELOG.md#4102---2021-12-09

There is a new PHP image that should also expose port 9003, which may resolve some issues.
